"""
Export a reference trajectory for the JS<->Python cross-check.
================================================================================
Runs the verified Python dynamic bicycle through a control sequence that
exercises all the dynamics (accelerate, slalom, brake, hard corner) and writes
the parameters + controls + resulting trajectory to web/xcheck_ref.js as an
injected global. web/xcheck.html replays the SAME controls through car.js and
compares the two implementations.

ASCII-only; run with: python -u
"""

import json
import numpy as np
from car_dynamic import DynamicBicycle, DoubleTrack
from bridge_modal import BridgeModal

OUT = "../web/xcheck_ref.js"


def control(t, q):
    """A sequence that excites longitudinal + lateral + yaw dynamics."""
    if t < 3.0:
        delta, thr = 0.0, 1.0                    # accelerate straight
    elif t < 8.0:
        delta = np.radians(6.0) * np.sin(2 * np.pi * (t - 3) / 2.5)  # slalom
        thr = 0.2
    elif t < 10.0:
        delta, thr = 0.0, -0.8                   # brake
    else:
        delta, thr = np.radians(5.0), 0.3        # steady corner
    return [delta, thr]


def roll(car, q0, dt, n):
    """Run a control sequence; return (controls, trajectory)."""
    q = np.array(q0, float)
    controls, traj = [], [list(q0)]
    for k in range(n):
        u = control(k * dt, q)
        controls.append([float(u[0]), float(u[1])])
        q = car.rk4_step(q, u, dt)
        traj.append(q.tolist())
    return controls, traj, q


def case(car, extra_params=None):
    dt, n, q0 = 0.005, 2600, [0, 0, 0, 12.0, 0, 0]
    controls, traj, q = roll(car, q0, dt, n)
    params = dict(m=car.m, Iz=car.Iz, a=car.a, b=car.b, h=car.h,
                  track=car.track, mu=car.mu, Cd=car.Cd, area=car.area,
                  rho=car.rho, g=car.g)
    if extra_params:
        params.update(extra_params)
    return dict(params=params, dt=dt, q0=q0, controls=controls, traj=traj), q


def bridge_case():
    """Record a moving-load crossing: per-step (P, a, a_mid) and the resulting
    mid-span deflection, for the JS bridge cross-check."""
    br = BridgeModal(L=40.0, EI=8.4e10, m_bar=12000.0, zeta=0.02, n_modes=4)
    P, v, dt = 12753.0, 30.0, 1e-3
    T = br.L / v
    n_steps = int(np.ceil((T + 1.5) / dt))
    state = np.zeros(2 * br.n)
    xm = br.L / 2
    steps, w_mid = [], [0.0]
    for k in range(n_steps):
        t = k * dt
        a0 = v * t
        am = v * (t + 0.5 * dt)
        a0 = float(a0) if a0 <= br.L else None
        am = float(am) if (am is not None and am <= br.L) else None
        steps.append([a0, am])
        state = br.rk4_step(state, dt, P, a0, am)
        w_mid.append(float(br.deflection(state, [xm])[0]))
    params = dict(L=br.L, EI=br.EI, m_bar=br.m_bar, zeta=br.zeta, n_modes=br.n)
    return dict(params=params, P=P, dt=dt, steps=steps, w_mid=w_mid)


def main():
    bike, qb = case(DynamicBicycle())
    dt = DoubleTrack(tllt_f=0.55, mu_load=0.10)
    dtrack, qd = case(dt, extra_params=dict(mu_load=dt.tyre.mu_load,
                                            tllt_f=dt.tllt_f))
    bridge = bridge_case()
    payload = dict(bicycle=bike, doubletrack=dtrack, bridge=bridge)
    with open(OUT, "w") as f:
        f.write("// generated by py/export_xcheck.py -- DO NOT EDIT\n")
        f.write("const XCHECK_REF = ")
        json.dump(payload, f)
        f.write(";\n")
    print(f"wrote {OUT}")
    print(f"  bicycle    final vx={qb[3]:.3f} Y={qb[1]:.3f} psi={qb[2]:.4f}")
    print(f"  doubletrack final vx={qd[3]:.3f} Y={qd[1]:.3f} psi={qd[2]:.4f}")
    print(f"  bridge     peak |w_mid|={max(abs(w) for w in bridge['w_mid'])*1e3:.3f} mm")


if __name__ == "__main__":
    main()
